language: ruby
rvm:
  - "2.3.0"
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 72101ad377aa0cba0b9e02986b6a3e7ddee416ce336c31de9bc2502705c46c8e
services:
  - elasticsearch
before_script:
  - psql -c 'create database litebooru_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:schema:load db:test:prepare db:seed test
