production:
  adapter: postgresql
  encoding: unicode
  database: litebooru
  host: localhost
  pool: 5
  username: litebooru
  password: <% ENV['DB_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: litebooru_development
  host: localhost
  pool: 5
  username: litebooru
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: litebooru_test
  host: localhost
  pool: 5
  username: litebooru
